#!/bin/sh

alias=$1
shift

if [ -r "$HOME/.pgalias" ]; then
    . "$HOME/.pgalias"
fi

eval flags=\$$alias

if [ -z "$flags" -o -z "$alias" ]; then
    echo "unknown alias '$alias'"
    exit 1
fi

exec psql $flags $@

